apiVersion: v1
kind: Service
metadata:
  name: appfiber-service
  namespace: app-fiber-dev
  labels:
    app: appfiber-deployment
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007
  selector:
    app: appfiber-deployment